### ISSUE TITLE
Missing pretrained model——trained_classifier_model_999.pt

### ISSUE THREAD

**Issue by PersistLu** [shiwentao00/Pocket2Drug#4]
hi, I was trying to reproduce your code and i couldn't find it(trained_classifier_model_999.pt).This file is mentioned in the pretrained_model in the encoder_config section of train.yaml.Can you provide the corresponding pre-training files?

**Comment by shiwentao00** [comment]
Hello, the pretrained model can be found along with the dataset in the osf repo:https://osf.io/qacwj/

**Comment by PersistLu** [comment]
Sorry to bother you again, the connection(https://osf.io/qacwj/) you provided does not have the model of the graph neural network mentioned in the paper and code.
![1](https://user-images.githubusercontent.com/52986379/182049204-b2293ab1-cfee-4208-a4cc-d0e3b9d30a60.png)

**Comment by shiwentao00** [comment]
pocket2drug.pt is the pretrained model.

**Comment by PersistLu** [comment]
Thanks a lot.
